#define ARENA_WIDTH 800
#define ARENA_HEIGHT 600

#define PIXEL_LENGTH 10

#define LEFT_WALL 0
#define RIGHT_WALL ARENA_WIDTH
#define NORTH_WALL 0
#define SOUTH_WALL ARENA_HEIGHT

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 10
#define PLAYER_LIVES 3
#define PLAYER_SPEED 200 // pixels/sec

#define MAX_BULLETS_PLAYER 3
#define MAX_BULLETS_ALIENS 10

#define BULLET_WIDTH 4
#define BULLET_HEIGHT 10
#define BULLET_SPEED 50

#define ALIEN_WIDTH 40
#define ALIEN_HEIGHT 25
#define ALIEN_SPACING 20

#define ALIENS_STARTING_Y 50
#define AMOUNT_ALIEN_COLS 12
#define AMOUNT_ALIEN_ROWS 5

#define ALIEN_SPEED 10
